# These are supported funding model platforms

buy_me_a_coffee: pekkaprime

# You can also add these later:
# github: [your-github-username]
# patreon: your-patreon-username
# ko_fi: your-ko-fi-username
